version: 2

models:
  - name: customers
    config:
      schema: mart
      materialized: table
    description: "Customer dimension table with lifetime value metrics"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer first name"
      - name: last_name
        description: "Customer last name"
      - name: first_order
        description: "Date of customer's first order"
      - name: most_recent_order
        description: "Date of customer's most recent order"
      - name: number_of_orders
        description: "Total number of orders placed by customer"
      - name: customer_lifetime_value
        description: "Total amount spent by customer across all orders"

  - name: orders
    config:
      schema: mart
      materialized: table
    description: "Order fact table with payment method breakdowns"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null
          - relationships:
              arguments:
                to: customers
                field: customer_id
      - name: order_date
        description: "Date the order was placed"
      - name: status
        description: "Current order status"
        tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: credit_card_amount
        description: "Amount paid via credit card"
      - name: coupon_amount
        description: "Amount paid via coupon"
      - name: bank_transfer_amount
        description: "Amount paid via bank transfer"
      - name: gift_card_amount
        description: "Amount paid via gift card"
      - name: amount
        description: "Total order amount"
